# Data Preprocessing

In [12]:
import pandas as pd
import numpy as np

## Dataset path defination

In [13]:
#raw data paths

train_raw_path = "../data/raw/CMAPSSData/train_FD004.txt"
test_raw_path = "../data/raw/CMAPSSData/test_FD004.txt"
rul_test_raw_path = "../data/raw/CMAPSSData/RUL_FD004.txt"

stats_path = "../data/meta/regime_stats.csv"

In [14]:
#processed data paths

train_processed_path = "../data/processed/train_FD004.csv"
val_processed_path = "../data/processed/validation_FD004.csv"
test_processed_path = "../data/processed/test_FD004.csv"
rul_test_raw_path = "../data/raw/CMAPSSData/RUL_FD004.txt"

In [15]:
selected_sensors = ['T24', 'T30', 'T50', 'P30', 'Nf', 'Nc', 'epr', 'Ps30', 'NRf', 'NRc', 'htBleed']

### Preprocess train set

In [16]:
%run ../src/preprocess.py

In [8]:
train_set, val_set = preprocess_data(file_path=train_raw_path, stats_path=stats_path, train_save_path=train_processed_path, val_save_path=val_processed_path, test_size=0.15, random_state=42, is_train=True, rul_cap=125)

Identified 6 unique operating regimes.
Normalization complete using stats from ../data/meta/regime_stats.csv
--- Data Split Summary ---
Total Engines: 249
Train Engines: 211 (52436 rows)
Val Engines:   38 (8813 rows)

In [9]:
train_set.head()

,unit_id,cycle,op_regime,T24,T30,T50,P30,Nf,Nc,epr,Ps30,NRf,NRc,htBleed,target_rul
0,1,1,5,-0.693905,-1.554268,-1.429294,-0.828586,-0.797788,-1.174632,-1.857537,-0.977167,-0.443547,-0.516716,-0.767811,125
1,1,2,4,-2.472241,-0.887933,-1.357091,-1.467589,-1.660474,-0.878468,-1.406369,-1.415886,-1.907184,-1.373377,-2.277316,125
2,1,3,5,-0.938760,-1.589528,-0.974887,-0.798325,-0.786558,-1.377407,-1.857537,-1.079192,-0.518879,-0.962343,-1.211200,125
3,1,4,5,-1.022615,-1.803366,-0.866800,-0.805706,-0.794045,-1.129522,-0.412956,-1.011175,-0.330549,-0.450496,-1.654590,125
4,1,5,3,-1.654742,-0.935484,-1.763136,-0.908397,-0.910789,-1.440557,-5.356662,-0.861269,-1.031613,-1.035006,-1.271973,125

In [10]:
val_set.head()

,unit_id,cycle,op_regime,T24,T30,T50,P30,Nf,Nc,epr,Ps30,NRf,NRc,htBleed,target_rul
0,7,1,0,1.853096,0.401212,1.120086,-0.768164,0.375437,-0.818445,-0.354268,0.743740,0.443709,-0.840364,0.769095,125
1,7,2,4,1.226115,-0.878890,0.428542,-0.477800,-0.247688,-1.019310,0.342885,0.667641,0.036391,-1.141439,0.103648,125
2,7,3,0,0.686724,0.274479,0.987532,-0.500010,0.308101,-0.421476,-0.354268,0.473171,0.107412,-1.154380,1.348804,125
3,7,4,5,-0.599988,-0.515789,0.997150,-0.790575,-0.814633,-0.921491,-0.412956,0.723250,-1.121536,-0.735459,0.118968,125
4,7,5,0,0.647845,1.182482,0.232284,-0.664362,0.308101,-0.651874,-0.354268,0.777561,0.040153,-1.193555,0.769095,125

In [17]:
test_set = preprocess_data(file_path=test_raw_path, stats_path=stats_path, test_save_path=test_processed_path, is_train=False)

Identified 6 unique operating regimes.
Normalization complete using stats from ../data/meta/regime_stats.csv

In [18]:
test_set.head()

,unit_id,cycle,op_regime,T24,T30,T50,P30,Nf,Nc,epr,Ps30,NRf,NRc,htBleed
0,1,1,4,-1.291915,-0.371015,-2.446687,-1.269631,-1.611757,-1.362157,-1.406369,-1.804340,-1.670162,-1.185586,-1.682075
1,1,2,3,-1.343792,-0.773920,-2.045346,-1.254529,-0.958268,-1.064417,-5.356662,-2.395297,-0.986834,-1.234205,-0.574973
2,1,3,5,-0.844843,-1.929621,-2.206859,-0.829324,-0.784687,-1.434780,-1.857537,-1.555309,-0.594211,-0.717547,-1.654590
3,1,4,5,-0.858260,-1.978531,-2.054655,-0.833384,-0.792173,-1.626606,-1.857537,-0.841134,-0.782542,-0.296344,-1.654590
4,1,5,5,1.124059,-0.461192,-0.892168,1.222563,1.232928,-0.310538,-0.412956,-2.235476,-0.895540,-1.439453,0.562357